// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmKygszWB9ojYtxNniGMvquDG9u1bDaDc',
    appId: '1:186180895446:web:06594670344d10700a3f77',
    messagingSenderId: '186180895446',
    projectId: 'bus-tracking-750d8',
    authDomain: 'bus-tracking-750d8.firebaseapp.com',
    storageBucket: 'bus-tracking-750d8.firebasestorage.app',
    measurementId: 'G-320SYBDX23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3J_87jzLKLvDdLVVPOWGY-tXB3O_HnoY',
    appId: '1:186180895446:android:048901d3ba9c03750a3f77',
    messagingSenderId: '186180895446',
    projectId: 'bus-tracking-750d8',
    storageBucket: 'bus-tracking-750d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZhalWYOb7d5JvV_-skxUPwzsC_WqI74Q',
    appId: '1:22376328148:ios:08fe2a0c547e0ab135c441',
    messagingSenderId: '22376328148',
    projectId: 'events-college',
    storageBucket: 'events-college.appspot.com',
    iosClientId:
        '22376328148-cv9i2hgn7th1kq9h0lodqdk8g1319880.apps.googleusercontent.com',
    iosBundleId: 'com.example.gpsAnouncer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZhalWYOb7d5JvV_-skxUPwzsC_WqI74Q',
    appId: '1:22376328148:ios:08fe2a0c547e0ab135c441',
    messagingSenderId: '22376328148',
    projectId: 'events-college',
    storageBucket: 'events-college.appspot.com',
    iosClientId:
        '22376328148-cv9i2hgn7th1kq9h0lodqdk8g1319880.apps.googleusercontent.com',
    iosBundleId: 'com.example.gpsAnouncer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmKygszWB9ojYtxNniGMvquDG9u1bDaDc',
    appId: '1:186180895446:web:de2cfcf01d067a620a3f77',
    messagingSenderId: '186180895446',
    projectId: 'bus-tracking-750d8',
    authDomain: 'bus-tracking-750d8.firebaseapp.com',
    storageBucket: 'bus-tracking-750d8.firebasestorage.app',
    measurementId: 'G-XCV96ZJ98H',
  );
}
